[package]
name = "classyc"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.18", features = ["derive"] }
classyvm = { path = "../classyvm" }
classyclib = { path = "../classyclib" }
colored = "2.0.0"
color-eyre = "0.6.2"
classy_syntax = { path = "../classy_syntax" }
