[package]
name = "classyc"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.18", features = ["derive"] }
classy_vm = { path = "../classyvm" }
classy_c = { path = "../classyclib" }
colored = "2.0.0"
color-eyre = "0.6.2"
